### ISSUE TITLE
does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by pavelpetrovic** [PositronicsLab/Moby#10]
0%] Building CXX object CMakeFiles/Moby.dir/src/AABB.cpp.o
[  1%] Building CXX object CMakeFiles/Moby.dir/src/ArticulatedBody.cpp.o
In file included from /usr/include/unicode/utypes.h:38:0,
                 from /usr/include/unicode/ucnv_err.h:88,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/local/Moby/include/Moby/XMLTree.h:14,
                 from /usr/local/Moby/src/ArticulatedBody.cpp:10:
/usr/include/unicode/umachine.h:376:13: error: ‘char16_t’ does not name a type
     typedef char16_t UChar;

cmake failed to add "-std=c++11" to flags.make
